
# don't automatically trigger builds from commits
# this pipeline is for manually packaging releases on the Osprey 4 website
# use a different pipeline for CI/CD builds
trigger: none

jobs:
  - job: build
    timeoutInMinutes: 20
    strategy:
      matrix:
        Linux:
          imageName: ubuntu-latest

    pool:
      vmImage: $(imageName)

    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            echo 'Hello world'
            uname -a

#  - task: Gradle@3
#    inputs:
#      gradleWrapperFile: 'gradlew'
#      tasks: 'serverRelease'
#      publishJUnitResults: false
#      javaHomeOption: 'JDKVersion'
#      sonarQubeRunAnalysis: false
#      spotBugsAnalysis: false
