
# This file configures a build system in Azure Pipelines.
# https://dev.azure.com/donaldlab/osprey/_build
# Osprey uses it to build the code on multiple platforms (eg Linux, Windos, Mac),
# so deveploers don't need to find computers with the right hardware/OS combo to make releases.

# This pipeline is for manually packaging releases on the Osprey 4 website.
# If you're looking for CI/CD builds, try the ci-pipelines.yml file.

# don't automatically trigger builds from commits, this is for manual releases
trigger: none

jobs:
  - job: build
    timeoutInMinutes: 20
    strategy:
      matrix:
        Linux:
          imageName: ubuntu-latest
          gradleWrapper: gradlew

    pool:
      vmImage: $(imageName)

    steps:

      - task: JavaToolInstaller@0
        # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/java-tool-installer?view=azure-devops
        inputs:
          # JDK 17 is installed by default on Microsoft agents, all three platforms, Eclipse Temurin release
          # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software
          versionSpec: '17'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'

      - task: Gradle@3
        # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/gradle?view=azure-devops
        inputs:
          gradleWrapperFile: '$(gradleWrapper)'
          tasks: 'serverRelease'
